# Generated by Django 5.0.7 on 2024-07-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, default='', max_length=255, verbose_name='image URI')),
                ('img_file', models.ImageField(blank=True, default='', upload_to='users', verbose_name='image file')),
                ('hash', models.CharField(blank=True, default='', max_length=100, verbose_name='image hash')),
            ],
        ),
    ]
