# Generated by Django 5.0.7 on 2024-07-26 16:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_file',
            field=models.ImageField(blank=True, default='', upload_to=api.models.upload_to, verbose_name='image file'),
        ),
    ]
