# Generated by Django 5.0.7 on 2024-07-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uri',
        ),
    ]
