# Generated by Django 5.0.7 on 2024-08-12 12:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_remove_image_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('status', models.CharField(choices=[('CLEARED', 'waste cleared'), ('INPROGRESS', 'in progress'), ('AVAILABLE', 'available for cleanup')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326, verbose_name='location')),
                ('cleaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastereport_cleaners', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('ACCEPT_POST', 'Accepted post'), ('CANCEL_TASK', 'Cancelled task'), ('UPDATED_POST', 'Updated a Post'), ('ADDED_POST', 'Added a Post')], max_length=20, verbose_name='Waste Report Activity')),
                ('activity_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Activity Timestamp')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastereport')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='wastereport',
            constraint=models.CheckConstraint(check=models.Q(('posted_by', models.F('cleaner')), _negated=True), name='no_self_post_accept_task'),
        ),
    ]
