# Generated by Django 5.0.7 on 2024-08-07 09:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_remove_image_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLEARED', 'Waste Cleared'), ('PENDING', 'Pending Removal'), ('URGENT', 'Urgent Cleanup')], default='PENDING', max_length=20)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326, verbose_name='location')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='WasteReportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('CLEANUP', 'Waste Report Cleanup'), ('UPDATE_POST', 'Updated a Post'), ('ADD_POST', 'Added a Post')], max_length=20, verbose_name='Waste Report Activity')),
                ('activity_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Activity Timestamp')),
                ('performed_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastereport')),
            ],
        ),
    ]
