# Generated by Django 5.0.7 on 2024-07-29 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereportactivity',
            name='activity_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activity Timestamp'),
        ),
        migrations.AlterField(
            model_name='wastereportactivity',
            name='performed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
