# Generated by Django 5.0.7 on 2024-08-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereportactivity',
            name='activity',
            field=models.CharField(choices=[('ACCEPT_POST', 'Accepted post'), ('CANCEL_TASK', 'Cancelled task'), ('FINISH_TASK', 'Finish task'), ('UPDATED_POST', 'Updated a Post'), ('ADDED_POST', 'Added a Post')], max_length=20, verbose_name='Waste Report Activity'),
        ),
    ]
