# Generated by Django 5.0.7 on 2024-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('CLEARED', 'Waste Cleared'), ('PENDING', 'Pending Removal'), ('URGENT', 'Urgent Cleanup')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
