# Generated by Django 5.0.7 on 2024-09-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_alter_wastereportactivity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereportactivity',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.wastereport'),
        ),
    ]
