# Generated by Django 5.0.7 on 2024-09-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_wastereportactivity_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='points count')),
                ('redeemed', models.BooleanField(verbose_name='points redemed')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointsRedeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_date', models.DateTimeField(verbose_name='claimed date')),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_assisted_by', to=settings.AUTH_USER_MODEL)),
                ('cleaner_points', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='waste.cleanerpoints')),
            ],
        ),
    ]
