# Generated by Django 5.0.7 on 2024-09-17 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_cleanerpoints_pointsredeem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointsRedeem',
            new_name='RedeemRecord',
        ),
    ]
