# Generated by Django 5.0.7 on 2024-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_rename_pointsredeem_redeemrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerpoints',
            name='count',
            field=models.IntegerField(default=0, verbose_name='points count'),
        ),
    ]
