# Generated by Django 5.0.7 on 2024-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_alter_cleanerpoints_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerpoints',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='points redemed'),
        ),
    ]
