# Generated by Django 5.0.7 on 2024-09-19 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0008_alter_cleanerpoints_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerpoints',
            name='count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='points count'),
        ),
    ]
