# Generated by Django 5.0.7 on 2024-09-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privateannouncement',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='publicannouncement',
            options={'ordering': ['-date_created']},
        ),
    ]
