# Generated by Django 5.0.7 on 2024-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_systemnotification_alter_privateannouncement_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateannouncement',
            name='code',
            field=models.CharField(choices=[('WASTE', 'Waste'), ('POINTS', 'Points'), ('ANNOUNCEMENTS', 'Announcements')], null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='privateannouncement',
            name='code_entity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='code entity id'),
        ),
    ]
